AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: OpenTelemetry Python Lambda layer for Python
Resources:
  api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: api
      TracingEnabled: true
      OpenApiVersion: 3.0.2
  function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      CodeUri: ./function
      Description: Build OTel Python Lambda Sample from scratch
      MemorySize: 512
      Timeout: 15
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonS3FullAccess
      Environment:
        Variables:
          AWS_LAMBDA_EXEC_WRAPPER: /opt/python/otel-instrument
          OTEL_LOG_LEVEL: "DEBUG"
          OTEL_EXPORTER_OTLP_ENDPOINT: "http://localhost:4318/"
          OTEL_TRACES_SAMPLER: "always_on"
      Tracing: Active
      Layers:
        - !Ref OTelLayer
        - arn:aws:lambda:us-west-2:184161586896:layer:opentelemetry-collector-amd64-0_10_0:3
      Events:
        getEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref api
            Path: /
            Method: GET
  OTelLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: opentelemetry-python
      Description: Opentelemetry Python layer
      ContentUri: ./otel
      CompatibleRuntimes:
        - python3.8
        - python3.9
        - python3.10
        - python3.11
    Metadata:
      BuildMethod: makefile
