receivers:
  otlp:
    protocols:
      http:
        endpoint: "localhost:4318"

processors:
  batch:
  decouple:

exporters:
  debug:
    #verbosity: detailed
    verbosity: basic
  otlp:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"

service:
  pipelines:
    traces:
      receivers: [otlp]
      #processors: [batch, decouple]
      #exporters: [otlp]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      exporters: [debug]
    logs:
      receivers: [otlp]
      exporters: [debug]
