name: "Manual Build (Collector)"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        architecture: [ amd64, arm64 ]
    outputs:
      COLLECTOR_VERSION: ${{ steps.save-collector-version.outputs.COLLECTOR_VERSION }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.1'
      - name: Build Collector
        run: make -C collector package GOARCH=${{ matrix.architecture }}
      - name: Upload Collector Artifact
        uses: actions/upload-artifact@v4
        with:
          name: opentelemetry-collector-layer-${{ matrix.architecture }}.zip
          path: ${{ github.workspace }}/collector/build/opentelemetry-collector-layer-${{ matrix.architecture }}.zip
      - name: Save Collector Version
        if: ${{ matrix.architecture == 'amd64' }}
        id: save-collector-version
        shell: bash
        # `./collector -v` output is in the form `v0.75.0`
        run: |
          COLLECTOR_VERSION=$( ${{ github.workspace }}/collector/build/extensions/collector -v)
          echo "COLLECTOR_VERSION=$COLLECTOR_VERSION" >> $GITHUB_OUTPUT
